FROM osrf/ros:kinetic-desktop-full

ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1

RUN apt-get update && apt-get install -y ros-kinetic-turtlebot && \
apt-get install -y ros-kinetic-turtlebot-apps && \
apt-get install -y ros-kinetic-turtlebot-interactions && \
apt-get install -y ros-kinetic-turtlebot-simulator && \
apt-get install -y ros-kinetic-kobuki-ftdi && \
apt-get install -y ros-kinetic-ar-track-alvar-msgs && \
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc && \
echo "export TURTLEBOT_GAZEBO_WORLD_FILE=/opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world" >> ~/.bashrc
